
[context.production]
environment = {CI = false}

[[redirects]]
from = "/"
status = 200
to = "/index.html"

[[redirects]]
from = "/collection"
status = 200
to = "/index.html"

[[redirects]]
from = "/product"
status = 200
to = "/index.html"
